fix(tracer): add http mapping attributes to transformer
GoogleCloudPlatform/opentelemetry-operations-js pull request #217
Opened 2020-12-17 14:31 UTC by sinoohe

Fixes #214
list of all http attributes are here: https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/http.md#common-attributes
I tried to add all of them
also note that in python they did it in this way:
https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/blob/c3772de4cf50950f1d51685ff3bbf0e46ee026df/opentelemetry-exporter-google-cloud/src/opentelemetry/exporter/cloud_trace/__init__.py#L367

2020-12-21 16:27 UTC, aabmass requested changes
Thanks for the PR, just a few comments

2020-12-21 16:27 UTC, aabmass commented on packages/opentelemetry-cloud-trace-exporter/src/transform.ts
> +const HTTP_ATTRIBUTE_MAPPING: {[key: string]: string} = {
The python impl you found was done most recently, and I think has the best mapping we can do right now. I need to get with the Cloud Trace folks to finalize these. Quite a few of the ones here don't appear in https://cloud.google.com/trace/docs/reference/v1/rest/v1/projects.traces#get. Did they actually work?

2020-12-21 16:27 UTC, aabmass commented on packages/opentelemetry-cloud-trace-exporter/src/transform.ts
> +  'http.target': '/http/target',
not in https://cloud.google.com/trace/docs/reference/v1/rest/v1/projects.traces#get

2020-12-21 16:27 UTC, aabmass commented on packages/opentelemetry-cloud-trace-exporter/src/transform.ts
> +    '/http/response_content_length_uncompressed',
not in https://cloud.google.com/trace/docs/reference/v1/rest/v1/projects.traces#get

In the python impl we mapped these to `/http/(request|response)/size` https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/blob/c3772de4cf50950f1d51685ff3bbf0e46ee026df/opentelemetry-exporter-google-cloud/src/opentelemetry/exporter/cloud_trace/__init__.py#L373-L374

2020-12-21 16:27 UTC, aabmass commented on packages/opentelemetry-cloud-trace-exporter/src/transform.ts
> +  'http.server_name': '/http/server_name',
not in https://cloud.google.com/trace/docs/reference/v1/rest/v1/projects.traces#get

2020-12-21 16:27 UTC, aabmass commented on packages/opentelemetry-cloud-trace-exporter/src/transform.ts
> +  'http.client_ip': '/http/client_ip',
not in https://cloud.google.com/trace/docs/reference/v1/rest/v1/projects.traces#get

2020-12-21 16:27 UTC, aabmass commented on packages/opentelemetry-cloud-trace-exporter/src/transform.ts
> +  'http.path': '/http/path',
This one's not in https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/http.md#common-attributes

2020-12-23 06:05 UTC, sinoohe commented
@aabmass I removed all additional fields. it's now the same as python's implementation

2020-12-23 18:20 UTC, aabmass approved these changes
Awesome, thanks again!

2020-12-23 18:20 UTC, merged