fix(resource-detector): properly detect zone on AppEngine standard
GoogleCloudPlatform/opentelemetry-operations-js pull request #715
Opened 2024-05-03 22:34 UTC by aabmass

Fixes https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/issues/655

It turns out GAE standard environment's metadata server returns a zone string like `projects/myproject/zones/us15`. Here are HTTP logs I printed out from a sample app:

```json
{
  "jsonPayload": {
    "message": "gaxios metadata request",
    "responseData": "projects/<project>/zones/us15",
    "requestUrl": "http://169.254.169.254/computeMetadata/v1/instance/zone"
  },
  "resource": {
    "type": "gae_app",
    "labels": {
      "zone": "us15",
      "version_id": "20240503t222051",
      "project_id": "otel-starter-project",
      "module_id": "default"
    }
  }
}
```

I updated the tests and manually tested a sample app on GAE standard writing metrics: 
![image](https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/assets/1510004/41f12b54-c3b0-4163-88e4-de15c23628b6)

2024-05-04 18:49 UTC, psx95 commented on packages/opentelemetry-resource-util/src/detector/detector.ts
> +    console.log('Got GAE standard zone=%s and region=%s', zone, region);
These were probably debug statements.

2024-05-04 19:14 UTC, psx95 commented
- The [Java Resource detector implementation](https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/blob/da9f22582113d93e2b23cc4ffaf42f294b03fb6b/detectors/resources-support/src/main/java/com/google/cloud/opentelemetry/detection/GoogleAppEngine.java#L44) does not seem to have this issue.

- The [Python resource detector](https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/tree/main/opentelemetry-resourcedetector-gcp/src/opentelemetry/resourcedetector/gcp_resource_detector) does not seem to support GAE. Is this correct ?

2024-05-04 19:15 UTC, psx95 requested changes
Nit: The `console.log` statements could be removed.

The change looks good.

2024-05-06 14:55 UTC, aabmass commented on packages/opentelemetry-resource-util/src/detector/detector.ts
> +    console.log('Got GAE standard zone=%s and region=%s', zone, region);
Oops thanks

2024-05-06 14:59 UTC, aabmass commented
> * The [Java Resource detector implementation](https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/blob/da9f22582113d93e2b23cc4ffaf42f294b03fb6b/detectors/resources-support/src/main/java/com/google/cloud/opentelemetry/detection/GoogleAppEngine.java#L44) does not seem to have this issue.

I think it does have the issue. [This test](https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/blob/da9f22582113d93e2b23cc4ffaf42f294b03fb6b/detectors/resources-support/src/test/java/com/google/cloud/opentelemetry/detection/GCPPlatformDetectorTest.java#L319-L320) doesn't provide the slash separated string for GAE standard and the detector just returns the zone directly

2024-05-06 15:10 UTC, dashpole approved these changes

2024-05-06 16:17 UTC, psx95 commented
> > * The [Java Resource detector implementation](https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/blob/da9f22582113d93e2b23cc4ffaf42f294b03fb6b/detectors/resources-support/src/main/java/com/google/cloud/opentelemetry/detection/GoogleAppEngine.java#L44) does not seem to have this issue.
> 
> I think it does have the issue. [This test](https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/blob/da9f22582113d93e2b23cc4ffaf42f294b03fb6b/detectors/resources-support/src/test/java/com/google/cloud/opentelemetry/detection/GCPPlatformDetectorTest.java#L319-L320) doesn't provide the slash separated string for GAE standard and the detector just returns the zone directly

We might need to add a test to prevent regression, but going by the [implementation of `metadataConfig.getZone()`](https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/blob/da9f22582113d93e2b23cc4ffaf42f294b03fb6b/detectors/resources-support/src/main/java/com/google/cloud/opentelemetry/detection/GCPMetadataConfig.java#L67), it does not look like there would be an issue as it is similar to what is being done in this fix.

2024-05-06 16:18 UTC, psx95 approved these changes

2024-05-07 03:02 UTC, aabmass commented
> We might need to add a test to prevent regression, but going by the [implementation of `metadataConfig.getZone()`](https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/blob/da9f22582113d93e2b23cc4ffaf42f294b03fb6b/detectors/resources-support/src/main/java/com/google/cloud/opentelemetry/detection/GCPMetadataConfig.java#L67), it does not look like there would be an issue as it is similar to what is being done in this fix.

Here is a test update https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/pull/341 thanks

2024-05-07 03:02 UTC, merged